services:
  storageSync:
    image: 'golang:1.25'
    container_name: 'storage_sync'
    working_dir: '/app'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - '.:/app' # DO NOT FIX THIS (you need your rclone binary file and modified .config.json)
      - "./.config:/root/.config" # DO NOT FIX THIS
      - '/volume1/aivyssuser:/nas_aivyssuser' # 'source (in NAS):destination (in docker)' + ./config/.config.json (in cloud storage)
      - '/volume1/plex/music:/nas_plex/music' # 'source (in NAS):destination (in docker)' + ./config/.config.json (in cloud storage)
      - '/volume1/plex/movies:/nas_plex/movies' # 'source (in NAS):destination (in docker)' + ./config/.config.json (in cloud storage)
      - '/volume1/homes/aivyssuser:/nas_homes_aivyssuser' # 'source (in NAS):destination (in docker)' + ./config/.config.json (in cloud storage)
      - '/volume1/immich_aivyssuser:/nas_immich' # 'source (in NAS):destination (in docker)' + ./config/.config.json (in cloud storage)
    command: go run main.go